#!/bin/bash
#
# install http://code.google.com/p/amazon-simpledb-cli/
# and http://developer.amazonwebservices.com/connect/entry.jspa?externalID=1136
# WARNING: make sure to install the required packages of the second as well

export JAVA_HOME="location to your java home"
export EC2_PRIVATE_KEY="location to your private key file"
export EC2_CERT="location to your certificate"
export EC2_HOME="location to your ec2 home"
export AWS_ACCESS_KEY_ID="your aws access key id"
export AWS_SECRET_ACCESS_KEY="your aws secret access key"
PATH=$PATH:$HOME/bin:$EC2_HOME/bin 

region="eu-west-1"

now=$(date +"%Y-%m-%d %H:%M:%S")

snapshots=$(simpledb query snapshot "['expires' < '${now}']")

for snapshot in $snapshots
do
    simpledb delete snapshot $snapshot
    ec2-delete-snapshot $snapshot --region $region
done
